// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team4524.robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

	public static final int frontLeftMotor = 0;
	public static final int rearLeftMotor = 2;
	public static final int frontRightMotor = 1;
	public static final int rearRightMotor = 4;
	public static final int leftEncoderChannel1 = 0;
	public static final int leftEncoderChannel2 = 1;
	public static final int rightEncoderChannel1 = 3;
	public static final int rightEncoderChannel2 = 2;
	public static final int rangefinder = 6;

	public static int gyro;
	private static final int gearBotsGyro = 1;
	private static final int pacGyro = 2;

	public static double leftDistancePerPulse;
	public static double rightDistancePerPulse;
	private static final double badLeftDistancePerPulse = .00610;
	private static final double badRightDistancePerPulse = 0.00435;
	private static final double goodLeftDistancePerPulse = .00442;
	private static final double goodRightDistancePerPulse = .00442;

	public static void init() {
		if (!Robot.isReal()) { // Converts to feet
			leftDistancePerPulse = (4.0/* in */ * Math.PI)
					/ (360.0 * 12.0/* in/ft */);
			rightDistancePerPulse = (4.0/* in */ * Math.PI)
					/ (360.0 * 12.0/* in/ft */);
			if (Robot.robotChoice == "pacgoat") {
				gyro = pacGyro;
			} else if (Robot.robotChoice == "gearbots") {
				gyro = gearBotsGyro;
			}
		} else if (Robot.robotChoice == "goodrobot") {
			leftDistancePerPulse = goodLeftDistancePerPulse;
			rightDistancePerPulse = goodRightDistancePerPulse;
		} else if (Robot.robotChoice == "badrobot") {
			leftDistancePerPulse = badLeftDistancePerPulse;
			rightDistancePerPulse = badRightDistancePerPulse;
		}
	}
}
