// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team4524.robot;

import org.usfirst.frc.team4524.robot.Robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

	public class DriveTrainMap {
		public static final int frontLeftMotor = 1;
		public static final int rearLeftMotor = 2;
		public static final int frontRightMotor = 3;
		public static final int rearRightMotor = 4;
		public static final int leftEncoderChannel1 = 1;
		public static final int leftEncoderChannel2 = 2;
		public static final int rightEncoderChannel1 = 3;
		public static final int rightEncoderChannel2 = 4;
		public static final int rangefinder = 6;
		public static final int gyro = 2;

	}

	public class FuelCollector {

	}

	public class FuelPickupDropoff {

	}

	public class RopeClimbier {

	}

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
